services:
  postgres:
    image: postgres:16-alpine
    container_name: underwwwater-postgres
    restart: always
    environment:
      POSTGRES_USER: underwwwater_user
      POSTGRES_PASSWORD: underwwwater_password
      POSTGRES_DB: underwwwater_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - underwwwater-network

volumes:
  postgres_data:

networks:
  underwwwater-network:
    driver: bridge
