services:
  postgres:
    image: postgres:16-alpine
    container_name: underwwwater-postgres
    restart: always
    environment:
      POSTGRES_USER: underwwwater_user
      POSTGRES_PASSWORD: underwwwater_password
      POSTGRES_DB: underwwwater_db
      POSTGRES_SCHEMA: underwwwater
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - underwwwater-network

  maildev:
    image: maildev/maildev
    container_name: underwwwater-maildev
    restart: always
    ports:
      - '1080:1080'
      - '1025:1025'
    networks:
      - underwwwater-network

volumes:
  postgres_data:

networks:
  underwwwater-network:
    driver: bridge
