version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: plongee-postgres
    restart: always
    environment:
      POSTGRES_USER: plongee_user
      POSTGRES_PASSWORD: plongee_password
      POSTGRES_DB: plongee_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - plongee-network

volumes:
  postgres_data:

networks:
  plongee-network:
    driver: bridge
